/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeibullRouteImport } from './routes/weibull'
import { Route as UniformeRouteImport } from './routes/uniforme'
import { Route as ParetoRouteImport } from './routes/pareto'
import { Route as NormalEstandarRouteImport } from './routes/normal-estandar'
import { Route as NormalRouteImport } from './routes/normal'
import { Route as LogNormalRouteImport } from './routes/log-normal'
import { Route as GumbelMinimoRouteImport } from './routes/gumbel-minimo'
import { Route as GumbelMaximoRouteImport } from './routes/gumbel-maximo'
import { Route as GammaRouteImport } from './routes/gamma'
import { Route as ExponencialRouteImport } from './routes/exponencial'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WeibullRoute = WeibullRouteImport.update({
  id: '/weibull',
  path: '/weibull',
  getParentRoute: () => rootRouteImport,
} as any)
const UniformeRoute = UniformeRouteImport.update({
  id: '/uniforme',
  path: '/uniforme',
  getParentRoute: () => rootRouteImport,
} as any)
const ParetoRoute = ParetoRouteImport.update({
  id: '/pareto',
  path: '/pareto',
  getParentRoute: () => rootRouteImport,
} as any)
const NormalEstandarRoute = NormalEstandarRouteImport.update({
  id: '/normal-estandar',
  path: '/normal-estandar',
  getParentRoute: () => rootRouteImport,
} as any)
const NormalRoute = NormalRouteImport.update({
  id: '/normal',
  path: '/normal',
  getParentRoute: () => rootRouteImport,
} as any)
const LogNormalRoute = LogNormalRouteImport.update({
  id: '/log-normal',
  path: '/log-normal',
  getParentRoute: () => rootRouteImport,
} as any)
const GumbelMinimoRoute = GumbelMinimoRouteImport.update({
  id: '/gumbel-minimo',
  path: '/gumbel-minimo',
  getParentRoute: () => rootRouteImport,
} as any)
const GumbelMaximoRoute = GumbelMaximoRouteImport.update({
  id: '/gumbel-maximo',
  path: '/gumbel-maximo',
  getParentRoute: () => rootRouteImport,
} as any)
const GammaRoute = GammaRouteImport.update({
  id: '/gamma',
  path: '/gamma',
  getParentRoute: () => rootRouteImport,
} as any)
const ExponencialRoute = ExponencialRouteImport.update({
  id: '/exponencial',
  path: '/exponencial',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exponencial': typeof ExponencialRoute
  '/gamma': typeof GammaRoute
  '/gumbel-maximo': typeof GumbelMaximoRoute
  '/gumbel-minimo': typeof GumbelMinimoRoute
  '/log-normal': typeof LogNormalRoute
  '/normal': typeof NormalRoute
  '/normal-estandar': typeof NormalEstandarRoute
  '/pareto': typeof ParetoRoute
  '/uniforme': typeof UniformeRoute
  '/weibull': typeof WeibullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exponencial': typeof ExponencialRoute
  '/gamma': typeof GammaRoute
  '/gumbel-maximo': typeof GumbelMaximoRoute
  '/gumbel-minimo': typeof GumbelMinimoRoute
  '/log-normal': typeof LogNormalRoute
  '/normal': typeof NormalRoute
  '/normal-estandar': typeof NormalEstandarRoute
  '/pareto': typeof ParetoRoute
  '/uniforme': typeof UniformeRoute
  '/weibull': typeof WeibullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exponencial': typeof ExponencialRoute
  '/gamma': typeof GammaRoute
  '/gumbel-maximo': typeof GumbelMaximoRoute
  '/gumbel-minimo': typeof GumbelMinimoRoute
  '/log-normal': typeof LogNormalRoute
  '/normal': typeof NormalRoute
  '/normal-estandar': typeof NormalEstandarRoute
  '/pareto': typeof ParetoRoute
  '/uniforme': typeof UniformeRoute
  '/weibull': typeof WeibullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/exponencial'
    | '/gamma'
    | '/gumbel-maximo'
    | '/gumbel-minimo'
    | '/log-normal'
    | '/normal'
    | '/normal-estandar'
    | '/pareto'
    | '/uniforme'
    | '/weibull'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/exponencial'
    | '/gamma'
    | '/gumbel-maximo'
    | '/gumbel-minimo'
    | '/log-normal'
    | '/normal'
    | '/normal-estandar'
    | '/pareto'
    | '/uniforme'
    | '/weibull'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/exponencial'
    | '/gamma'
    | '/gumbel-maximo'
    | '/gumbel-minimo'
    | '/log-normal'
    | '/normal'
    | '/normal-estandar'
    | '/pareto'
    | '/uniforme'
    | '/weibull'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExponencialRoute: typeof ExponencialRoute
  GammaRoute: typeof GammaRoute
  GumbelMaximoRoute: typeof GumbelMaximoRoute
  GumbelMinimoRoute: typeof GumbelMinimoRoute
  LogNormalRoute: typeof LogNormalRoute
  NormalRoute: typeof NormalRoute
  NormalEstandarRoute: typeof NormalEstandarRoute
  ParetoRoute: typeof ParetoRoute
  UniformeRoute: typeof UniformeRoute
  WeibullRoute: typeof WeibullRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weibull': {
      id: '/weibull'
      path: '/weibull'
      fullPath: '/weibull'
      preLoaderRoute: typeof WeibullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uniforme': {
      id: '/uniforme'
      path: '/uniforme'
      fullPath: '/uniforme'
      preLoaderRoute: typeof UniformeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pareto': {
      id: '/pareto'
      path: '/pareto'
      fullPath: '/pareto'
      preLoaderRoute: typeof ParetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normal-estandar': {
      id: '/normal-estandar'
      path: '/normal-estandar'
      fullPath: '/normal-estandar'
      preLoaderRoute: typeof NormalEstandarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normal': {
      id: '/normal'
      path: '/normal'
      fullPath: '/normal'
      preLoaderRoute: typeof NormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-normal': {
      id: '/log-normal'
      path: '/log-normal'
      fullPath: '/log-normal'
      preLoaderRoute: typeof LogNormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gumbel-minimo': {
      id: '/gumbel-minimo'
      path: '/gumbel-minimo'
      fullPath: '/gumbel-minimo'
      preLoaderRoute: typeof GumbelMinimoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gumbel-maximo': {
      id: '/gumbel-maximo'
      path: '/gumbel-maximo'
      fullPath: '/gumbel-maximo'
      preLoaderRoute: typeof GumbelMaximoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamma': {
      id: '/gamma'
      path: '/gamma'
      fullPath: '/gamma'
      preLoaderRoute: typeof GammaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exponencial': {
      id: '/exponencial'
      path: '/exponencial'
      fullPath: '/exponencial'
      preLoaderRoute: typeof ExponencialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExponencialRoute: ExponencialRoute,
  GammaRoute: GammaRoute,
  GumbelMaximoRoute: GumbelMaximoRoute,
  GumbelMinimoRoute: GumbelMinimoRoute,
  LogNormalRoute: LogNormalRoute,
  NormalRoute: NormalRoute,
  NormalEstandarRoute: NormalEstandarRoute,
  ParetoRoute: ParetoRoute,
  UniformeRoute: UniformeRoute,
  WeibullRoute: WeibullRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
